[package]
name = "lithia-powder"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.25.2"
glam = { version = "0.33.3", features = ["bytemuck"] }
itertools = "0.15.0"
sdl3 = { version = "0.18.4", features = ["build-from-source-static"] }
shaderc = "0.10.1"

[dev-dependencies]
clippy = "0.0.302"
